defaults:
    - model: bert

train:
    fast_dev_run: false
    epochs: 10
    add_ner: true
    drop_mimic_deid: true

data:
    mimic_data_dir: "/home/vs428/project/MIMIC/files/mimiciii/1.4/"
    n2c2_data_dir: "/home/vs428/project/n2c2/2022/Data/"

pretrained:
    spacy_assessment: "/home/vs428/Documents/prodigy/assessment_model/model-best"
    spacy_plan: "/home/vs428/Documents/prodigy/plan_subsection_model/model-best"

hardware:
    gpu: true
